### ISSUE TITLE
Radare2 support

### ISSUE THREAD

**Issue by XVilka** [IDArlingTeam/IDArling#1]
Could you please kindly consider the option of supporting radare2 as an instance for this platform? Because - why not? See issue https://github.com/radare/radare2/issues/7410 for the reference. Feel free to open issues in radare2 repo if you need to fix something for your plugin to work.

**Comment by NeatMonster** [comment]
This is definitely something we have in mind, but in the long term. We would like the plug-in to be a bridge between different RE software (IDA Pro, Binary Ninja, radare2), but we're currently focusing on IDA Pro integration because it is the one we're most accustomed too (and probably the most popular).

We're currently iterating very quickly in term of internal design, so would also like to wait before working on integration with other software. For now, we're working toward releasing a first beta version in the coming weeks. I'm working on getting rid of Twisted and relying solely on built-in libraries for networking, which would allow for an integrated server (for quick collaborative RE sessions) besides the dedicated one. @patathor is working on implementing the last missing features, and making the plug-in more robust.

This project definitively needs more testing, and we haven't yet figured out how to proceed.

**Comment by zadlg** [comment]
I could help on that. I know (a little bit) how radare2 works

**Comment by NeatMonster** [comment]
@zadlg We're always looking for contributions! But sadly I don't think the project is nearly close to a state where we can start implementing cross-software synchronization. If would like to help with the short-term todo list though, feel free to contact us on IRC (or Jabber ;)) for more information.

**Comment by NeatMonster** [comment]
@zadlg It is relevant, but this is so far in our long-term plans (and I personally won't be working on it - maybe on BinaryNinja) that I think it is okay to focus only on IDA at the moment. Like @SilverBut mentioned, because we're able to run the server outside of IDA, I think the current separation is enough. Maybe the events and event callbacks could be split into two files, but that will be easy to do in due time.

**Comment by XVilka** [comment]
Never expected a different answer.

**Comment by patateqbool** [comment]
We will accept any PR related to R2, :).
