### ISSUE TITLE
Backup IDBs Feature

### ISSUE THREAD

**Issue by hacksysteam** [IDArlingTeam/IDArling#47]
Hi @NeatMonster ,

It would be great to have a functionality to have server automatically save the uploaded IDBs to a GIT server or whatever is good.

I had submitted the same request but can't seem to find it in the issue list, so filing it again.

Thanks.

**Comment by NeatMonster** [comment]
I'm not a big fan of the idea of adding Git support for the server. But would storing every revision of the database under a different name (maybe suffixed by the date) work for you?

**Comment by hacksysteam** [comment]
What happens when the sever is dead for some reason. I requirement is not specifically for GIT. 
My more emphasis was on backup the IDBs to some other locations.
Do you have anything in mind?

**Comment by NeatMonster** [comment]
I personally believe that not it isn't the job of IDArling to backup the databases stored on the server. Maybe an user interested in backups of the server could use a cron job to copy/export the files elsewhere?

Anyway, I wouldn't mind other people's input on the matter. @patateqbool @SilverBut @NyaMisty

**Comment by patateqbool** [comment]
Actually, I agree with @NeatMonster. This is not IDArling job to backup the databases, and other software, I think noticeably to rdiff-backup, do this task much better than we could do it.

What are your points of view @SilverBut @NyaMisty ?

**Comment by SilverBut** [comment]
I can not see the point of implementing it in IDArling server side, since:

1. When the server is dead, users will be disconnected, reverse engineering jobs are desynced, and even if you can get it back again, conflict command packets may still have a chance of making things worse. Maybe we should have an excellent way to solve the un-synced problem before backing up IDBs. (I heard @NyaMisty have some ideas, lol)
2. There are several other ways to implement this without modifying the server side, including `Dropbox`, `rsync` and `inotify`. We would better keep it simple.

However, although it is not a must-implement function for IDArling, maybe we can have a deploy script and related scripts to help for this feature?

**Comment by hacksysteam** [comment]
@SilverBut , yes, I know it's not a must thing to implement. Deploy scripts would be absolutely fine.

**Comment by NeatMonster** [comment]
I think @SilverBut summed it up perfectly. I won't be writing those deploy scripts because we have a lot of other features to implement, but if anyone is willing to work on this, it would be greatly appreciated.

**Comment by patateqbool** [comment]
I think we can close this issue, @hacksysteam @NeatMonster @SilverBut ?

**Comment by hacksysteam** [comment]
@patateqbool Sure.
