### ISSUE TITLE
Annoying "Analyzing..." window

### ISSUE THREAD

**Issue by SilverBut** [IDArlingTeam/IDArling#58]
An anonymous user reported this enhancement request.

> When a change is synced on the local machine, the "analyzing" window from IDA will come up and last for a few milliseconds. During the analyze, a user can not do anything, which is kind of interruptive for users.

**Comment by NyaMisty** [comment]
This is caused by request refresh actions. If the dialog only lasts for a few ms, then human won't even notice it.
But, it will be a disaster when user is open several big functions' pseudo code view in the background.
Currently we are refreshing all related views when a event arrives, no matter whether user is focusing on the tab. This is causing the IDA gets very very slow when events arrived.

So we can have several improvements:
1. Don't refresh the inactive tabs
2. Make the IDA not showing the "Analysing" dialog, but doing the analysis in the background like the auto-analysis

As for point 2, I think that we can contact with Hexrays team for some help ;)

**Comment by NeatMonster** [comment]
A few things that we should look into:

- checking if the pseudo-code view is [`visible`](https://www.hex-rays.com/products/decompiler/manual/sdk/structvdui__t.shtml#a43a01a09a5c33439a43e6dbab2ed2097)
- [`refresh_view`](https://www.hex-rays.com/products/decompiler/manual/sdk/structvdui__t.shtml#a90e071c55e25c1bffcbc76933d156249) takes a boolean, maybe we don't need to set it to true
- maybe we can use [`refresh_ctext`](https://www.hex-rays.com/products/decompiler/manual/sdk/structvdui__t.shtml#a736c952a9401001762e734d5a53de726) instead of `refresh_view`

Also, re-reading the [Hex-Rays header file](https://www.hex-rays.com/products/decompiler/manual/sdk/hexrays_8hpp.shtml) makes me realize that we don't handle `numforms` (user defined number formats) and `unions` (user defined union field selections).

**Comment by NyaMisty** [comment]
We really should dig deeper into this issue, during the DEFCON, the prompt is really bothering and distracting.

PS: for those two that really tricky, I've only heard that them on update hisory hahaha.
