### ISSUE TITLE
Seems the function comment in Hex-Rays not synchonrized

### ISSUE THREAD

**Issue by NyaMisty** [IDArlingTeam/IDArling#8]
Comments like this won't be sent to server :(
![image](https://user-images.githubusercontent.com/5344431/43702040-0d9ea644-998b-11e8-9138-42eb84420cc8.png)

**Comment by NeatMonster** [comment]
Thank you for using IDArling and reporting the issues you encounter @NyaMisty!

Function comments are probably stored somewhere else, somewhere that we missed obviously. Hex-Rays support is still very much a work in progress, as it requires digging into the internals of IDA. If someone is interested in implementing this, that would be much appreciated, otherwise I will try to do it when I'll have a chance.

**Comment by NyaMisty** [comment]
Haha *good first issue* is quite funny. I love it very much!
But it seems that this function can only be implemented using inline hook :(

**Comment by NeatMonster** [comment]
Actually, it wasn't that tricky. From [Edit Block Comment](https://www.hex-rays.com/products/decompiler/manual/cmd_block_cmts.shtml) page of the user manual, I learned that:
> If applied to the function declaration line, this command edits the function comment. This comment is shared with IDA: it is the same as the function comment in IDA.

Searching for "function comment" in the SDK documentation led to the [`get_func_cmt`](https://www.hex-rays.com/products/ida/support/sdkdoc/funcs_8hpp.html#aeadbb1e0b11eae2e34730ede51d1ed38) and [`set_func_cmt`](https://www.hex-rays.com/products/ida/support/sdkdoc/funcs_8hpp.html#a49070bb3dbf2ca55720d20db3a44c9f0) functions. From there, it was only a matter of finding the right [`idb_event`](https://www.hex-rays.com/products/ida/support/sdkdoc/namespaceidb__event.html), which turned out to be [`cmt_range_changed`](https://www.hex-rays.com/products/ida/support/sdkdoc/namespaceidb__event.html#a0feb6e648b4e6e3f0ed954abea672784a61ac3acc89a3dc48f2d89250f4041df2). A few lines of code later and the function and segment comments are hooked!
